name: Tests and checks on push

on:
  push:
    branches:
      - rewrite

jobs:
  run-checks-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress E2E tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          browser: chrome
        env:
          BASE_URL: http://localhost:4455
          PORT: 4455
          DB_PATH: db.sqlite3
          NODE_ENV: test
      - name: Prettier
        run: npm run prettier:check
      - name: Lint TS
        run: npm run lint:ts
      - name: Stylelint
        run: npm run lint:styles
      - name: Typecheck
        run: npm run typecheck
