name: Updates translation progress

on:
  push:
    branches:
      - rewrite

jobs:
  update-translation-progress-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Update translation progress issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun run check-translation-jsons
          gh issue edit 1104 --body-file ./translation-progress.md
